### ISSUE TITLE
Sign in button persists on menu bar

### ISSUE THREAD

**Issue by poma** [poma/MinimalisticView#1]
I don't know how to hide it via XAML because all relevant classes are marked as internal by MS. The only workaround I know of is to remove this button by deleting registry key `HKCU\Software\Microsoft\VisualStudio\14.0_Config\MainWindowFrameControls\<Guid>`

**Comment by disklosr** [comment]
Hi, just wanted to let you know that I found another extension that hides the sign in button. It's called Hide Main Menu. Hope this helps

**Comment by poma** [comment]
Thanks, that helped a lot. Issue is fixed now.
