### ISSUE TITLE
VS 2017 is crashing after todays update

### ISSUE THREAD

**Issue by 7mPx** [poma/MinimalisticView#12]
The title says it all.
Can I get a crashreport somewhere from VS?

**Comment by poma** [comment]
Does it display anything or the window silently disappears?

**Comment by 7mPx** [comment]
The window just disappears

**Comment by poma** [comment]
This is most likely caused by dependency update in latest commits. Try starting Visual Studio with logging enabled https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2019

**Comment by poma** [comment]
Looks like I got Threading dependency wrong. I'll try to compile test version while you are looking for logs

**Comment by 7mPx** [comment]
So i got a created log file without extension and the ActivityLog.xls in the attached zip

[log.zip](https://github.com/poma/MinimalisticView/files/3050663/log.zip)

**Comment by wzhymxz** [comment]
How do I not open the vs2017 disable control

**Comment by poma** [comment]
You can temporarily remove the extension from `AppData/Local/Microsoft/VisualStudio/2017/Extensions`

**Comment by fyc132** [comment]
After updating today ,vs2017 Black Screen.

**Comment by poma** [comment]
Temporarily reverted latest commits and uploaded as a new version until this problem is solved

**Comment by cg31** [comment]
Maybe FeedbackPanel meends a null check before using? On VS2017, it could be null.

**Comment by poma** [comment]
Oh snap, I did this check but accidentally removed it during refactoring. You might be right.

**Comment by machinechina** [comment]
Also on  VS2019 , it crashs on startup window.
But RIGHT-click VS icon and select a recent solution works.

**Comment by theparticleman** [comment]
I just found this extension after installing VS2019 today. It is now officially my new favorite extension. If you need help testing it when you re-enable 2019 support, please let me know. I'm running both 2017 and 2019 and would love it to work in both.

**Comment by poma** [comment]
Fixed in #14
