### ISSUE TITLE
Installation failed - not installable on any currently installed products

### ISSUE THREAD

**Issue by markonius** [poma/MinimalisticView#3]
Hi!
I tried installing but I get the following error (from Install Log):
`2017-04-14 12:43:49 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.`
That is odd, since supported products are:
`Microsoft.VisualStudio.Community	Version : [15.0,16.0)`
And my version is:
`Found installed product - Microsoft Visual Studio Community 2015`

**Comment by markonius** [comment]
I'm stupid, I have version 14 (as stated in the about window).

**Comment by poma** [comment]
It worked for me on 14 but I had to rebuild for 15. Don't know how to build a single version for both (they are different only in references)

**Comment by markonius** [comment]
ok, thanks. I'm gonna rebuild it for 14
