### ISSUE TITLE
Titlebar hover debounce

### ISSUE THREAD

**Issue by trymnilsen** [poma/MinimalisticView#5]
At the moment the titlebar is shown immediately if the cursors hovers over the top of the window. Would it make sense to have an adjustable debounce time for opening/showing the titlebar?

**Comment by poma** [comment]
Is there any other software with similar behavior? 

For me personally immediately showing menu is the most comfortable way, but if delay is a common UI practice I can implement it. Also a delay after mouse leaves menu before it is hidden.

**Comment by poma** [comment]
Implemented in v2.3
